services:
  server:
    build:
      context: .
      target: prod
    ports:
      - "3000:3000"
    env_file:
      - .env.prod
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "512M"
    read_only: true
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
