name: Build & Deploy Docker image to Pi

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/nfc-reader:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/nfc-reader:latest

      - name: SSH into Raspberry Pi and deploy container
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/nfc-reader:latest
            docker stop nfc-reader || true
            docker rm nfc-reader || true
            docker run -d --restart=always \
              --name nfc-reader \
              --device=/dev/bus/usb \
              ${{ secrets.DOCKERHUB_USERNAME }}/nfc-reader:latest
